### ISSUE TITLE
Can we get CVPixelBuffer result instead of CMSampleBuffer?

### ISSUE THREAD

**Issue by oguzveozturk** [pinkjuice66/VideoStreaming#1]
Hi mate,
thanks for detailed explanation. I couldn't find anything better than your article on this subject.

but i can't get CVPixelBuffer from CMSampleBuffer.
**sampleBuffer.imageBuffer returns nil**

How can i do that?

**Comment by pinkjuice66** [comment]
Hello there.

If you are not able to get a CVPixelBuffer from the CMSampleBuffer, that means 
1. it doesn't contain a CVPixelBuffer or 
2. it contains CMBlockBuffer which is media data such as audio samples or a p-frame, an i-frame or
3. there's an error

I don't know where you try to get a CVPixelBuffer from the CMSampleBuffer but i'm pretty sure that you try to do it where there's no a CVPixelBuffer like after encoding or input data is audio sample.

If you can't find any solutions with this, please give me more context like your code base.

**Comment by oguzveozturk** [comment]
Thanks for the quick response,

I'm using true depth camera (or lidar). So i have two different content from AVCaptureDataOutputSynchronizerDelegate:
1 - depthBuffer -> type of CVPixelBuffer
2 - textureBuffer -> type of CMSampleBuffer (and contains CVPixelBuffer)

But for the simplicity i'm using only texture buffer for now.  There is no audio data in here. Just like your example.
And again for the simplicity i'm not sending data via network. Inside the apple's delegate method:
1- Just converting textureBuffer to Data with naluHandling (from your H264 Encoder)
2- After that immediately Data to CMSampleBuffer with naluParser and H264Decoder
3- In this state i need the MTLTexture for my MTKView and i'm creating this from CVPixelBuffer
4- So when i try to access CVPixelBuffer from the CMSampleBuffer it returns nil. 
5- Actually our codes very identical and I got the same result in your project. please try to access CVPixelBuffer before this line `layer.enqueue(sample)`

**Comment by pinkjuice66** [comment]
Hello. 

The problem is that you didn't decode the CMSampleBuffer, so it's still a i-frame or p-frame.
In my tutorial, i used AVSampleBufferDisplayLayer object which has the ability to decode the CMSampleBuffer, so i didn't need to decode the CMSampleBuffer.
But if you want to extract a CVPixelBuffer from the encoded CMSampleBuffer, you need to decode the CMSampleBuffer manually using VTDecompressionSession which is i mentioned in the part2. 

So all you need to do is just decode the CMSampleBuffer that you are handling now.

**Comment by oguzveozturk** [comment]
Okay then i will try it.
thanks again.

**Comment by QoT** [comment]
In iOS 17.4, there should be API that handles compressed and uncompressed frames and delivers decoded CVPixelBuffer:

https://developer.apple.com/documentation/avfoundation/avsamplebuffervideorenderer/4316233-displayedpixelbuffer
